config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users # , ActiveAdmin::Devise.config

  ActiveAdmin.routes(self)

  resources :categories, param: :title, only: [] do
    resources :books, only: :index
  end

  resources :books, only: :show do
    resources :reviews, only: :create
  end

  scope(path_names: { create: "create" }) do
    resource :carts do
      get "/", to: "carts#index"
    end
  end

  resources :users, only: [] do
    resources :orders, only: %i[create show]
  end

  scope "/checkout", controller: "checkout", as: "checkout" do
    get "address", to: "address"
    get "delivery", to: "delivery"
    get "payment", to: "payment"
    get "confirm", to: "confirm"
    get "complete", to: "complete"
  end

  resource :addresses, only: %i[new update] do
    put "check", to: "check"
  end

  root "home#home"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    if user.admin?
      can :manage, :all
    else
      can :read, Book
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/address.rb
# frozen_string_literal: true

class Address < ApplicationRecord
  belongs_to :user
end

app/models/author.rb
# frozen_string_literal: true

class Author < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/billing_address.rb
# frozen_string_literal: true

class BillingAddress < Address
  validates :first_name, length: { minimum: 3 }
end

app/models/book.rb
# frozen_string_literal: true

class Book < ApplicationRecord
  belongs_to :author
  belongs_to :category
  has_many :review, dependent: :destroy
  has_many :books_orders
  has_many :orders, through: :books_orders
  self.per_page = 12
end

app/models/books_order.rb
# frozen_string_literal: true

class BooksOrder < ApplicationRecord
  belongs_to :order
  belongs_to :book
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :book
end

app/models/category.rb
# frozen_string_literal: true

class Category < ApplicationRecord
  has_many :books, dependent: :destroy
end

app/models/order.rb
# frozen_string_literal: true

class Order < ApplicationRecord
  has_many :books_orders, dependent: :destroy
  has_many :books, through: :books_orders
  belongs_to :user
end

app/models/review.rb
# frozen_string_literal: true

class Review < ApplicationRecord
  belongs_to :book
  belongs_to :user
end

app/models/shipping_address.rb
# frozen_string_literal: true

class ShippingAddress < Address
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :shipping_address, dependent: :destroy
  has_one :billing_address, dependent: :destroy
  has_many :review, dependent: :destroy
  has_many :orders, dependent: :destroy
end

app/controllers/checkout_controller.rb
# frozen_string_literal: true

class CheckoutController < ApplicationController
  before_action :check_login

  def address
    cart = Cart.where(session: session[:current_user])
    cookies[:item_total] = cart.map { |i| i.book.price }.sum
    cookies[:order_total] = cookies[:item_total]
    cookies[:coupon] = cart.first.coupon || 0
  end

  def delivery; end

  def payment
    cookies[:delivery] = params[:delivery]
    cookies[:order_total] = cookies[:item_total].to_f - cookies[:coupon].to_f + DELIVERY[cookies[:delivery].to_sym].first.to_f
  end

  def confirm
    cookies.encrypted[:card_number] = params[:card_number]
    cookies.encrypted[:card_date] = params[:exp_date]
    cookies.encrypted[:card_name] = params[:card_name]
    cookies.encrypted[:card_cvv] = params[:cvv]
    @shipping = current_user.shipping_address
    @billing = current_user.billing_address
    @cart = count_book(Cart.where(session: session[:current_user])).sort
  end

  def complete
    @order = Order.find_by(number: params[:number_order])
    @cart = count_book(BooksOrder.where(order_id: @order.id)).sort
    @shipping = current_user.shipping_address
  end

  private

  def check_login
    return unless current_user.nil?

    redirect_to new_user_session_path, alert: "You must be logged in to perform the following actions"
  end

  def count_book(source)
    Hash[*source.group_by(&:book_id).map { |i| [Book.find(i.first), i.last&.size] }.flatten(1)]
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/checkout/_cart.html.haml
%table.table.table-hover
  %thead
    %tr
      %th
        %span.in-grey-600 Book
      %th.col-method
      %th
        %span.in-grey-600 Price
      %th
        %span.in-grey-600 Quantity
      %th
        %span.in-grey-600 Total
  %tbody
    - @cart.each do |book, count|
      %tr
        %td
          .general-img-wrap-table
            %img.cart-img-shadow.pull-left{src: book.cover, alt: "design-book"}
        %td
          %p.title= book.title
          %p.in-grey-600.fw-300= book.description
        %td
          %span.font-16.in-gold-500= number_to_currency(book.price, :unit => "€")
        %td
          %span.ml-30= count
        %td
          %span.font-16.in-gold-500= number_to_currency((book.price * count), :unit => "€")

app/views/checkout/_cart_xs.html.haml
- @cart.each do |book, count|
  .general-cart-item.divider-lg
    .general-img-wrap-table
      %img.cart-img-shadow{src: book.cover, alt: "design-book"}
    %p.title= book.title
    %P.in-grey-600.fw-300= book.description
    %table.table
      %tr
        %td
          %span.in-grey-600 Price
        %td
          %span.font-16.in-gold-500= number_to_currency(book.price, :unit => "€")
      %tr
        %td.vertical-middle
          %span.in-grey-600 Quantity
        %td
          %span= count
      %tr
        %td
          %span.in-grey-600 Subtotal
        %td
          %span.font-16.in-gold-500= number_to_currency((book.price * count), :unit => "€")

app/views/checkout/_form_address.html.haml
.form-group
  = form.label :first_name
  = form.text_field :first_name, value: type&.first_name, class: "form-control"
.form-group
  = form.label :last_name
  = form.text_field :last_name, value: type&.last_name, class: "form-control"
.form-group
  = form.label :address
  = form.text_field :address, value: type&.address, class: "form-control"
.form-group
  = form.label :city
  = form.text_field :city, value: type&.city, class: "form-control"
.form-group
  = form.label :zip
  = form.text_field :zip, value: type&.zip, class: "form-control"
.form-group
  = form.label :country
  = form.text_field :country, value: type&.country, class: "form-control"
.form-group.mb-60
  = form.label :phone
  = form.text_field :phone, value: type&.phone, placeholder: "Example +355 66 123 4567", class: "form-control"

app/views/checkout/_order.html.haml
.general-text-align.mb-60
  %p.in-gold-500.font-18 Order Summary
  %table.general-summary-table
    %tr
      %td
        %p.font-16 Item Total:
      %td
        %p.font-16= number_to_currency(cookies[:item_total], :unit => "€")
    %tr
      %td
        %p.font-16 Coupon:
      %td
        %p.font-16= number_to_currency((cookies[:coupon] || "0"), :unit => "€")
    %tr
      %td
        %p.font-16 Order Total:
      %td
        %p.font-16= number_to_currency(cookies[:order_total], :unit => "€")

app/views/checkout/address.html.haml
%main.container
  %h1.general-title-margin Checkout
  %ul.steps.list-inline
    %li.step.active
      %span.step-number 1
      %span.step-text.hidden-xs Address
    %li.step-divider
    %li.step
      %span.step-number 2
      %span.step-text.hidden-xs Delivery
    %li.step-divider
    %li.step
      %span.step-number 3
      %span.step-text.hidden-xs Payment
    %li.step-divider
    %li.step
      %span.step-number 4
      %span.step-text.hidden-xs Confirm
    %li.step-divider
    %li.step
      %span.step-number 5
      %span.step-text.hidden-xs Complete
  = form_with :url => check_addresses_path, method: "put" do |form|
    .hidden-xs.hidden-sm
      .row
        .col-md-5
          %h3.general-subtitle Billing Address
          %p.general-info-text all fields are required
        .col-md-5.col-md-offset-1
          %h3.general-subtitle Shipping Address
    .row
      .col-md-5.mb-40
        = form.fields_for :billing do |form|
          .visible-xs.visible-sm
            %h3.general-subtitle Billing Address
            %p.general-info-text all fields are required
          = render "form_address", type: current_user.billing_address, form: form
      .col-md-5.col-md-offset-1.mb-60
        #shipping
          = form.fields_for :shipping do |form|
            .visible-xs.visible-sm
              %h3.general-subtitle Shipping Address
            = render "form_address", type: current_user.shipping_address, form: form
        .form-group.checkbox
          %label.checkbox-label
            = form.check_box :use_billing, class: "checkbox-input", id: 'checkbox_shipping', value: "1", hidden: "true"
            %span.checkbox-icon
              %i.fa.fa-check
            %span.checkbox-text Use Billing Address
    = render "order"
    %button.btn.btn-default.center-block.mb-20{type: "submit"} Save and Continue

app/views/checkout/complete.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin Checkout
  %ul.steps.list-inline
    %li.step.done
      %span.step-number
        %i.fa.fa-check.step-icon
      %span.step-text.hidden-xs Address
    %li.step-divider
    %li.step.done
      %span.step-number
        %i.fa.fa-check.step-icon
      %span.step-text.hidden-xs Delivery
    %li.step-divider
    %li.step.done
      %span.step-number
        %i.fa.fa-check.step-icon
      %span.step-text.hidden-xs Payment
    %li.step-divider
    %li.step.done
      %span.step-number
        %i.fa.fa-check.step-icon
      %span.step-text.hidden-xs Confirm
    %li.step-divider
    %li.step.active
      %span.step-number 5
      %span.step-text.hidden-xs Complete
  .text-center.mb-40
    %h3.general-subtitle Thank You for your Order!
    %p.fw-300 An order confirmation has been has been sent to #{current_user.email}
  .row.mb-20
    .col-sm-6
      .visible-xs
        %p.general-order-number.mb-0 Order #R25314582
        %p.general-address.mb-30 October 29, 2016
      %p.general-address
        #{@shipping.first_name} #{@shipping.last_name}
        %br
        = @shipping.address
        %br
        #{@shipping.city} #{@shipping.zip}
        %br
        = @shipping.country
        %br
        Phone #{@shipping.phone}
    .col-sm-6.hidden-xs.text-right
      %p.general-order-number.mb-0 Order №#{params[:number_order]}
      %p.general-address.mb-30= @order.created_at.strftime("%B %d, %Y")
  .visible-xs
    = render "cart_xs"
  .hidden-xs.divider-lg.pt-20
    = render "cart"
  .text-center.general-text-right
    %p.in-gold-500.font-18 Order Summary
    %table.general-summary-table.general-summary-table-right.general-text-right
      %tr
        %td
          %p.font-16 Subtotal:
        %td
          %p.font-16= number_to_currency(@order.subtotal, :unit => "€")
      %tr
        %td
          %p.font-16 Coupon:
        %td
          %p.font-16= number_to_currency(@order.coupon, :unit => "€")
      %tr
        %td
          %strong.font-18 Order Total:
        %td
          %strong.font-18= number_to_currency(@order.order_total, :unit => "€")
  .text-center
    %a.button.btn.btn-default.mb-20{href: root_path} Back to Store

app/views/checkout/confirm.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin Checkout
  %ul.steps.list-inline
    %li.step
      %span.step-number 1
      %span.step-text.hidden-xs Address
    %li.step-divider
    %li.step
      %span.step-number 2
      %span.step-text.hidden-xs Delivery
    %li.step-divider
    %li.step
      %span.step-number 3
      %span.step-text.hidden-xs Payment
    %li.step-divider
    %li.step.active
      %span.step-number 4
      %span.step-text.hidden-xs Confirm
    %li.step-divider
    %li.step
      %span.step-number 5
      %span.step-text.hidden-xs Complete
  .row.mb-20
    .col-sm-3
      %h3.general-subtitle Shipping Address
      %p.general-address
        #{@shipping.first_name} #{@shipping.last_name}
        %a.span.general-edit{href: checkout_address_path} edit
        %br
        = @shipping.address
        %br
        #{@shipping.city} #{@shipping.zip}
        %br
        = @shipping.country
        %br
        Phone #{@shipping.phone}
    .col-sm-3
      %h3.general-subtitle Billing Address
      %p.general-address
        #{@billing.first_name} #{@billing.last_name}
        %a.span.general-edit{href: checkout_address_path} edit
        %br
        = @billing.address
        %br
        #{@billing.city} #{@billing.zip}
        %br
        = @billing.country
        %br
        Phone #{@billing.phone}
    .col-sm-3
      %h3.general-subtitle Shipments
      %p.general-address
        = DELIVERY[cookies[:delivery].to_sym].second
        %a.span.general-edit{href: checkout_delivery_path} edit
    .col-sm-3
      %h3.general-subtitle Payment Information
      %p.general-address
        ** ** ** #{cookies.encrypted[:card_number][-4..-1]}
        %a.span.general-edit{href: checkout_payment_path} edit
        %br
        #{cookies.encrypted[:card_date][0..2]}20#{cookies.encrypted[:card_date][-2..-1]}
  .visible-xs
    = render "cart_xs"
  .hidden-xs.divider-lg.pt-20
    = render "cart"
  .text-center.general-text-right
    = render "order"
  .text-center
    %a.button.btn.btn-default.mb-20{href: user_orders_path(number_order: "R#{Time.now.strftime("%m%d%H%M")}", user_id: current_user.id), "data-turbo-method": "post"} Place Order

app/views/checkout/delivery.html.haml
%main.container.general-main-wrap
  %h1.general-title-margin Checkout
  %ul.steps.list-inline
    %li.step
      %span.step-number 1
      %span.step-text.hidden-xs Address
    %li.step-divider
    %li.step.active
      %span.step-number 2
      %span.step-text.hidden-xs Delivery
    %li.step-divider
    %li.step
      %span.step-number 3
      %span.step-text.hidden-xs Payment
    %li.step-divider
    %li.step
      %span.step-number 4
      %span.step-text.hidden-xs Confirm
    %li.step-divider
    %li.step
      %span.step-number 5
      %span.step-text.hidden-xs Complete
  = form_with url: checkout_payment_path, method: :get do |form|
    .visible-xs
      - DELIVERY.each do |method, values|
        .general-cart-item.divider-lg-bottom
          %table.table
            %tr
              %td.col-half
                %span.in-grey-600 Method
              %td.col-half
                .form-group.radio.mt-0.mb-0
                  %label.radio-label
                    - if cookies[:delivery] == method.to_s
                      = form.radio_button :delivery, method, hidden: "true", class: "radio-input", checked: "checked"
                    - else
                      = form.radio_button :delivery, method, hidden: "true", class: "radio-input"
                    %span.radio-icon
                    %span.radio-text= values.second
            %tr
              %td
                %span.in-grey-600 Days
              %td
                %span.font-16.fw-300= values.last
            %tr
              %td
                %span.in-grey-600 Price
              %td
                %span.font-16.in-gold-500= values.first
    .hidden-xs.mb-res-50
      %table.table.table-hover
        %thead
          %tr
            %th.col-method
              %span.in-grey-600.ml-40 Method
            %th
              %span.in-grey-600 Days
            %th
              %span.in-grey-600 Price
        %tbody
          - DELIVERY.each do |method, values|
            %tr
              %td
                .form-group.radio.mt-0.mb-0
                  %label.radio-label
                    - if cookies[:delivery] == method.to_s
                      = form.radio_button :delivery, method, hidden: "true", class: "radio-input", checked: "checked"
                    - else
                      = form.radio_button :delivery, method, hidden: "true", class: "radio-input"
                    %span.radio-icon
                    %span.radio-text= values.second
              %td
                %span= values.last
              %td
                %span.font-16.in-gold-500= values.first
    = render "order"
    .text-center
      %button.btn.btn-default.mb-20{type: "submit"} Save and Continue

app/views/checkout/payment.html.haml
%main.container.mb-res-50
  %h1.general-title-margin Checkout
  %ul.steps.list-inline
    %li.step
      %span.step-number 1
      %span.step-text.hidden-xs Address
    %li.step-divider
    %li.step
      %span.step-number 2
      %span.step-text.hidden-xs Delivery
    %li.step-divider
    %li.step.active
      %span.step-number 3
      %span.step-text.hidden-xs Payment
    %li.step-divider
    %li.step
      %span.step-number 4
      %span.step-text.hidden-xs Confirm
    %li.step-divider
    %li.step
      %span.step-number 5
      %span.step-text.hidden-xs Complete
  %h3.general-subtitle Credit Card
  = form_with url: checkout_confirm_path, method: :get, class: "max-600" do |form|
    .form-group.has-error
      = form.label :card_number, class: "control-label input-label"
      = form.number_field :card_number, placeholder: "Card Number", class: "form-control", value: cookies[:card_number]
      %span.help-block Please enter a valid credit card number
    .row
      .col-sm-6
        .form-group
          = form.label :card_name, class: "control-label input-label"
          = form.text_field :card_name, placeholder: "Name On Card", class: "form-control", value: cookies[:card_name]
      .col-sm-3
        .form-group
          = form.label :exp_date, "MM / YY", class: "control-label input-label"
          = form.text_field :exp_date, placeholder: "MM / YY", class: "form-control", value: cookies[:card_date]
      .col-sm-3
        .form-group.relative.mb-80
          = form.label :cvv, "CVV", class: "control-label input-label"
          = form.text_field :cvv, placeholder: "CVV", class: "form-control", value: cookies[:card_cvv]
          %i.fa.fa-question-circle.general-form-help{title: "3-digit security code, usually found on the back of your card. American Express cards has 4-digit code, located on the front"}
    = render "order"
    .text-center
      %button.btn.btn-default.mb-80{type: "submit"} Save and Continue